elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/data:/usr/share/elasticsearch/data
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/patterns:/opt/logstash/patterns
  ports:
    - 5000:5000
  links:
    - elasticsearch
  environment:
    - LS_HEAP_SIZE=2048m
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - 5601:5601
  links:
    - elasticsearch
